# This configuration does not include a processing node
# Which makes for faster setup times
version: "2.1"
volumes:
  dbdata:
  appmedia:
services:
  db:
    image: webodm/webodm_db
    container_name: db
    expose:
      - "5432"
    volumes:
      - ${WO_DB_DIR}:/var/lib/postgresql/data:Z
    restart: unless-stopped
    oom_score_adj: -100
  webapp:
    image: webodm/webodm_webapp
    container_name: webapp
    entrypoint: /bin/bash -c "service cron start && chmod +x /webodm/*.sh && webpack --mode production && python manage.py collectstatic --noinput && python manage.py compilemessages -l zh_Hans && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\""
    volumes:
      - ${WO_MEDIA_DIR}:/webodm/app/media:z
      - ./app/models/task.py:/webodm/app/models/task.py:ro
      - ./app/api/tasks.py:/webodm/app/api/tasks.py:ro
      - ./app/migrations/0052_task_original_image_size.py:/webodm/app/migrations/0052_task_original_image_size.py:ro
      - ./app/static/app/js/components/TaskListItem.jsx:/webodm/app/static/app/js/components/TaskListItem.jsx:ro
      - ./app/api/tags.py:/webodm/app/api/tags.py:ro
      - ./coreplugins/taskwebhook:/webodm/coreplugins/taskwebhook:ro
      - ./locale/zh_Hans/LC_MESSAGES/djangojs.po:/webodm/locale/zh_Hans/LC_MESSAGES/djangojs.po:ro
      - ./webodm/settings.py:/webodm/webodm/settings.py:ro
      - ./app/boot.py:/webodm/app/boot.py:ro
      - ./app/templates/app/base.html:/webodm/app/templates/app/base.html:ro
      - ./app/templates/app/logged_in_base.html:/webodm/app/templates/app/logged_in_base.html:ro
      - ./app/static/app/img/zhihui-logo.png:/webodm/app/static/app/img/zhihui-logo.png:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${WO_PORT}:8000/tcp"
      - "${WO_PORT}:8000/udp"
    depends_on:
      - db
      - broker
      - worker
    environment:
      - WO_PORT
      - WO_HOST
      - WO_DEBUG
      - WO_BROKER
      - WO_DEV
      - WO_DEV_WATCH_PLUGINS
      - WO_SECRET_KEY
      - WEB_CONCURRENCY
    restart: unless-stopped
    oom_score_adj: 0
  broker:
    image: redis:7.0.10
    container_name: broker
    restart: unless-stopped
    oom_score_adj: -500
  worker:
    image: webodm/webodm_webapp
    container_name: worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - ${WO_MEDIA_DIR}:/webodm/app/media:z
      - ./app/models/task.py:/webodm/app/models/task.py:ro
      - ./app/migrations/0052_task_original_image_size.py:/webodm/app/migrations/0052_task_original_image_size.py:ro
      - ./coreplugins/taskwebhook:/webodm/coreplugins/taskwebhook:ro
      - ./webodm/settings.py:/webodm/webodm/settings.py:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - broker
    environment:
      - WO_BROKER
      - WO_DEBUG
      - WO_SECRET_KEY
      - WEB_CONCURRENCY
    restart: unless-stopped
    oom_score_adj: 250
