# Chaining this file to the main docker-compose file adds
# a default processing node instance. This is best for users
# who are just getting started with WebODM.

version: '2.1'
services:
  webapp:
    depends_on:
      - node-odx-1
    environment:
      - WO_DEFAULT_NODES
  node-odx-1:
    image: webodm/nodeodx:gpu
    container_name: node-odx-1
    volumes:
      - ./ODX-master/opendm/ogctiles.py:/code/opendm/ogctiles.py:ro
      - ./ODX-master/opendm/ogc_enu.py:/code/opendm/ogc_enu.py:ro
      - ./ODX-master/opendm/mesh_clipper.py:/code/opendm/mesh_clipper.py:ro
      - ./ODX-master/stages/odm_postprocess.py:/code/stages/odm_postprocess.py:ro
    expose:
      - "3000"
    restart: unless-stopped
    oom_score_adj: 500
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]
