# 基于现有 NodeODX GPU 镜像构建
FROM webodm/nodeodx:gpu

# 复制 ODX 自定义代码到镜像内部
COPY ODX-master/opendm/ogctiles.py /code/opendm/ogctiles.py
COPY ODX-master/opendm/ogc_enu.py /code/opendm/ogc_enu.py
COPY ODX-master/opendm/mesh_clipper.py /code/opendm/mesh_clipper.py
COPY ODX-master/stages/odm_postprocess.py /code/stages/odm_postprocess.py
